```toml
[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

**Explanation:**
* The `[build]` section explicitly defines the build command and the publish directory.
* The `[[redirects]]` section defines the same redirect rule as your `_redirects` file. Using `netlify.toml` is often considered more robust for redirects.
