import React, { useEffect, useState } from 'react';

// Figma-aligned TripForm: modern input styling, clear headers, helper text, responsive
function TripForm({ newItem, handleInputChange, onAddItem, onSaveEdit, onCancelEdit, openModal, isEditing }) {
  const [formData, setFormData] = useState(newItem);

  useEffect(() => {
    setFormData(newItem);
  }, [newItem]);

  const handleFormChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (handleInputChange) handleInputChange(e);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!formData.date || !formData.title || !formData.type) {
      openModal('Please fill in all required fields (Date, Type, Title).');
      return;
    }
    if (isEditing) {
      onSaveEdit(formData);
    } else {
      onAddItem(formData);
    }
  };

  return (
    <div className="p-6 bg-white rounded-lg shadow-md max-w-2xl mx-auto">
      <form onSubmit={handleSubmit}>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Date*</label>
            <input
              type="date"
              name="date"
              value={formData.date || ''}
              onChange={handleFormChange}
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
              required
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Type*</label>
            <select
              name="type"
              value={formData.type || 'roofed'}
              onChange={handleFormChange}
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
              required
            >
              <option value="roofed">Accommodation (roofed)</option>
              <option value="camp">Camp</option>
              <option value="enroute">Enroute / Travel</option>
              <option value="note">Note</option>
              <option value="ferry">Ferry</option>
              <option value="car">Car / Drive</option>
              <option value="plane">Plane / Flight</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Title*</label>
            <input
              type="text"
              name="title"
              value={formData.title || ''}
              onChange={handleFormChange}
              placeholder="e.g. Hotel Grand, Wine Tour"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
              required
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Location</label>
            <input
              type="text"
              name="location"
              value={formData.location || ''}
              onChange={handleFormChange}
              placeholder="e.g. Hobart, Cradle Mountain"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
          </div>
          {/* Est. Travel Time field removed as it is autogenerated */}
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Activities</label>
            <input
              type="text"
              name="activities"
              value={formData.activities || ''}
              onChange={handleFormChange}
              placeholder="e.g. Hiking, Museum, Food Tour"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Activity Link</label>
            <input
              type="url"
              name="activityLink"
              value={formData.activityLink || ''}
              onChange={handleFormChange}
              placeholder="Auto-generated based on type/location"
              className="w-full p-3 border border-gray-100 rounded-lg bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              title="This URL is auto-generated based on type and location, but you can edit it manually"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 mb-1">Status</label>
            <select
              name="status"
              value={formData.status || 'Unconfirmed'}
              onChange={handleFormChange}
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
            >
              <option value="Unconfirmed">Unconfirmed</option>
              <option value="Booked">Booked</option>
              <option value="Completed">Completed</option>
              <option value="Cancelled">Cancelled</option>
              <option value="Not booked">Not booked</option>
            </select>
          </div>
          <div className="lg:col-span-2">
            <label className="block text-xs font-semibold text-gray-500 mb-1">Photo URL(s)</label>
            <input
              type="text"
              name="photos"
              value={formData.photos || ''}
              onChange={handleFormChange}
              placeholder="Comma-separated photo URLs"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
              title="Enter photo URLs separated by commas, or leave blank"
            />
            <p className="text-xs text-gray-500 mt-1">Tip: Upload photos to a cloud service and paste URLs here</p>
          </div>
          <div className="lg:col-span-3">
            <label className="block text-xs font-semibold text-gray-500 mb-1">Notes</label>
            <textarea
              name="notes"
              value={formData.notes || ''}
              onChange={handleFormChange}
              placeholder="Notes (e.g., guest details, reminders)"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400"
              rows="2"
            ></textarea>
          </div>
        </div>
        <div className="flex justify-end space-x-4 mt-8">
          <button
            type="button"
            onClick={onCancelEdit}
            className="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-6 rounded-lg transition duration-300"
          >
            Cancel
          </button>
          <button
            type="submit"
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-6 rounded-lg transition duration-300 shadow"
          >
            {isEditing ? 'Save Changes' : 'Add Item'}
          </button>
        </div>
      </form>
    </div>
  );
}

export default TripForm;
